#!/usr/bin/env python3

import argparse
import subprocess

class InvalidBoardError(Exception):
    pass

class BoardInfo:
    def __init__(self, name, fqbn, port, macro):
        self.name = name
        self.fqbn = fqbn
        self.port = port
        self.macro = macro
class BoardMap:
    def __init__(self):
        self.boards = dict()
    def add_board(self, name, fqbn, port, macro=None):
        self.boards[name] = BoardInfo(name, fqbn, port, macro)
    def get_board(self, name):
        try:
            return self.boards[name]
        except ValueError as ve:
            raise InvalidBoardError(f'no board {name} available in map')

board_map = BoardMap()
board_map.add_board(
    name="elegoo_uno",
    fqbn="arduino:avr:uno",
    port="/dev/ttyACM0",
    macro="TARGET_UNO")
board_map.add_board(
    name="nodemcu",
    fqbn="esp8266:esp8266:nodemcuv2",
    port="/dev/ttyUSB0",
    macro="TARGET_NODEMCU")

def parse_args():
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
        description="""
        accu - arduino-cli compile upload
        this will compile and upload from the cli
        we should have an easy port thing or a mapping for ports
        microcontroller name and map the fqbn
        sketch is the folder with the sketch

        something like this:
            >> accu --port /dev/ttyACM0 --fully-qualified-board-name arduino:avr:uno --sketch sketch/path
        or maybe
            >> accu --micro-controller elegoo_uno --sketch sketch/path
        the above would require a mapping like this
            class BoardInfo:
                name
                fqbn
                port (may need to be changed at run time could have a default though)
            elegoo_uno = BoardInfo("elegoo_uno", "arduino:avr:uno", "/dev/ttyACM0")
            nodemcu = BoardInfo(...)
            board_map[elegoo_uno, nodemcu]

            >> accu --board-name "elegoo_uno" --port /dev/ttyACM0
        """,
        epilog="""
        EXAMPLES:
            compile, load, and monitor
            >> accu -n elegoo_uno -b -s <sketch_name> -l -p /dev/ttyACM0 -m 9600
            >> ac
        """)
    parser.add_argument("-b", "--build", action="store_true", default=False, help="flag to build firmware")
    parser.add_argument("-l", "--load", action="store_true", default=False, help="flag to load firmware")
    parser.add_argument("-s", "--sketch", help="path to sketch folder")
    parser.add_argument("-p", "--port", default=None, help="port to load to")
    parser.add_argument("-n", "--name", help="name of the board to load to")
    parser.add_argument("-m", "--monitor", dest="baud", default=None, help="connect with a serial monitor afterwards. using screen command. quit with '<ctrl-a>\'")
    parser.add_argument("-bp", "--build-properties", default=[], nargs="+")
    return parser.parse_args()

def main(args):
    if args.build:
        try:
            board_info = board_map.get_board(args.name)
        except InvalidBoardError as ibe:
            raise InvalidBoardError(ibe)
        else:
            build_properties = ""
            if board_info.macro is not None:
                build_properties = " --build-property "
                build_properties += f'build.extra_flags="-D{board_info.macro}" '
            if args.build_properties == "":
                raise NotImplementedError()
            # if len(args.build_properties) == 0:
            # else:
            #     for build_prop in args.build_properties:
            #         build_properties += f'build.extra_flags="-D{build_prop}" '
            build_cmd = f"arduino-cli compile --fqbn {board_info.fqbn} {args.sketch}{build_properties}"
            print(build_cmd)
            error = subprocess.run(build_cmd, check=True, shell=True)
    if args.load:
        try:
            board_info = board_map.get_board(args.name)
        except InvalidBoardError as ibe:
            raise InvalidBoardError(ibe)
        else:
            port = args.port if args.port is not None else board_info.port
            load_cmd = f"arduino-cli upload -p {port} --fqbn {board_info.fqbn} {args.sketch}"
            print(load_cmd)
            error = subprocess.run(load_cmd, check=True, shell=True)
    if args.baud is not None:
        try:
            board_info = board_map.get_board(args.name)
        except InvalidBoardError as ibe:
            raise InvalidBoardError(ibe)
        else:
            port = args.port if args.port is not None else board_info.port
            monitor_cmd = f"screen {args.port} {args.baud}"
            error = subprocess.run(monitor_cmd, check=True, shell=True)

if __name__ == "__main__":
    args = parse_args()
    main(args)
