# inventory.ini
[test]
ansible-test ansible_connection=docker ansible_user=testuser ansible_distribution=Fedora
ansible-test-u24 ansible_connection=docker ansible_user=testuser ansible_distribution=Ubuntu

# run with
# ansible-playbook -i inventory setup.yml --ask-become-pass
