# inventory.ini
[test-fedora]
# create a docker image first
# docker run --rm -d --name ansible-test-fedora fedora:43 /bin/bash -c "useradd -m -G wheel testuser && echo 'testuser:testpassword' | chpasswd && sleep infinity"
# test specifically this with
# ansible-playbook -i inventory setup.yml --ask-become-pass --limit test-fedora
ansible-test-fedora ansible_connection=docker ansible_user=testuser ansible_distribution=Fedora
[test-ubuntu]
# create a docker image first
# docker run --rm -d --name ansible-test-u24 ubuntu:24.04 /bin/bash -c "useradd -m -G sudo testuser && echo 'testuser:testpassword' | chpasswd && apt update && apt install sudo -y && sleep infinity"
# test specifically this with
# ansible-playbook -i inventory setup.yml --ask-become-pass --limit test-ubuntu
ansible-test-u24 ansible_connection=docker ansible_user=testuser ansible_distribution=Ubuntu

[framework12-fedora]
local-fedora43 ansible_connection=local ansible_distribution=Fedora ansible_user=rileytuttle
ssh-fedora43 ansible_connection=ssh ansible_host=fw12 ansible_distribution=Fedora ansible_user=rileytuttle

[framework12-ubuntu]
local-ubuntu24 ansible_connection=local ansible_distribution=Ubuntu ansible_user=rileytuttle
ssh-ubuntu24 ansible_connection=ssh ansible_host=fw12 ansible_distribution=Ubuntu ansible_user=rileytuttle
